services:
  db:
    image: postgres:14.17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    # volumes:
    #   # - database_data:/var/lib/postgresql/data
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  db_data:

  # POSTGRES_USER=user POSTGRES_PASSWORD=1234 POSTGRES_DB=mydatabase docker-compose up